databases:
  - name: quitotine-db
    plan: free
    databaseName: quitotine
    user: quitotine

services:
  # --- Backend API ---
  - type: web
    name: quitotine-api
    runtime: docker
    plan: free
    region: frankfurt
    dockerContext: ./backend
    # dockerfilePath: ./backend/Dockerfile   # csak ha nem standard nevű
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quitotine-db
          property: connectionString
      - key: API_PREFIX
        value: /api/v1
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "30"
      - key: ENVIRONMENT
        value: production
      # ezt később frissíted a frontend Render URL-re:
      - key: CORS_ORIGINS
        value: https://quitotine-frontend.onrender.com

  # --- Frontend (Vite Static) ---
  - type: web
    name: quitotine-frontend
    runtime: static
    plan: free
    region: frankfurt
    rootDir: ./frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://quitotine-api.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
